# Generated by Django 5.2.4 on 2026-05-29 05:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Running', 'Running'), ('Cycling', 'Cycling'), ('Weightlifting', 'Weightlifting'), ('Swimming', 'Swimming'), ('Walking', 'Walking')], max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('distance', models.FloatField(blank=True, help_text='Distance in km or miles', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
